[package]
name = "vex-sdk-desktop"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.94"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
fast_image_resize.workspace = true
line_drawing = "1.0.1"
image.workspace = true
parking_lot = "0.12.5"
tracing.workspace = true
vex-sdk.workspace = true
font-kit = { version = "0.14.3", default-features = false, features = [
    "loader-freetype",
], git = "https://github.com/servo/font-kit" }
pathfinder_geometry = "0.5.1"
freetype-sys = { version = "0.23.0", features = ["bundled"] }
thiserror.workspace = true
png = "0.18.1"
iceoryx2.workspace = true
derive_more = { workspace = true, features = ["as_ref", "from", "try_into"] }
roboscope-ipc = { version = "0.1.0", path = "../ipc", features = [] }
cfg-if = "1.0.4"
static_assertions = "1.1.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
itertools = "0.14.0"
socket2.workspace = true
