[package]
name = "examples"
version = "0.1.0"
publish = false
edition = "2024"

[workspace]
members = ["ipc", "viewer", "simulator"]

[dev-dependencies]
embedded-graphics = { version = "0.8.2", default-features = false }
tinybmp = "0.7.0"
tracing-subscriber = { version = "0.3.22" }
vex-sdk = "0.28.0"

[target.'cfg(target_os = "vexos")'.dev-dependencies]
vexide = { version = "0.8.0", features = ["full", "default-sdk"] }

[target.'cfg(not(target_os = "vexos"))'.dev-dependencies]
vexide = { version = "0.8.0", features = ["startup", "macros"] }
vex-sdk-desktop = { path = "./simulator" }

[patch.crates-io]
# Rust >=1.94 support
vexide = { git = 'https://github.com/vexide/vexide.git' }
