[package]
name = "roboscope-viewer"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
iceoryx2.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
ctrlc = { version = "3.5.2" }
fast_image_resize.workspace = true
image.workspace = true
roboscope-ipc = { version = "0.1.0", path = "../ipc" }
softbuffer = "0.4.8"
tracing.workspace = true
winit = "0.30.13"
clap = { version = "4.6.5", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
dispatch2 = "0.3.1"
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", features = ["NSThread"] }
objc2-app-kit = { version = "0.3.2", features = [
    "objc2-core-graphics",
    "NSImage",
    "NSView",
] }
objc2-core-graphics = { version = "0.3.2", features = [
    "CGDataProvider",
    "CGColorSpace",
] }
