[package]
name = "roboscope-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.1"
derive_more = { version = "2.1.1", features = ["try_into", "from", "debug", "deref"] }
iceoryx2 = "0.8.1"
socket2 = "0.6.3"
thiserror = "2.0.18"
tracing = "0.1.44"
vex-sdk = "0.28.0"

[features]
default = ["thread-safe"]
thread-safe = []

[dev-dependencies]
tracing-subscriber = "0.3.23"
