[package]
name = "roboscope-ipc"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "2.11.1"
derive_more = { workspace = true, features = ["try_into", "from", "debug", "deref"] }
iceoryx2.workspace = true
socket2.workspace = true
thiserror.workspace = true
tracing.workspace = true
vex-sdk.workspace = true

[features]
default = ["thread-safe"]
thread-safe = []

[dev-dependencies]
tracing-subscriber.workspace = true
